
package com.soap.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "GetAccountServiceImplService", targetNamespace = "http://service.soap.com/", wsdlLocation = "http://localhost:4500/soap/accounts?wsdl")
public class GetAccountServiceImplService
    extends Service
{

    private final static URL GETACCOUNTSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException GETACCOUNTSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName GETACCOUNTSERVICEIMPLSERVICE_QNAME = new QName("http://service.soap.com/", "GetAccountServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:4500/soap/accounts?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GETACCOUNTSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        GETACCOUNTSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public GetAccountServiceImplService() {
        super(__getWsdlLocation(), GETACCOUNTSERVICEIMPLSERVICE_QNAME);
    }

    public GetAccountServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), GETACCOUNTSERVICEIMPLSERVICE_QNAME, features);
    }

    public GetAccountServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, GETACCOUNTSERVICEIMPLSERVICE_QNAME);
    }

    public GetAccountServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GETACCOUNTSERVICEIMPLSERVICE_QNAME, features);
    }

    public GetAccountServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GetAccountServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GetAccountServiceImpl
     */
    @WebEndpoint(name = "GetAccountServiceImplPort")
    public GetAccountServiceImpl getGetAccountServiceImplPort() {
        return super.getPort(new QName("http://service.soap.com/", "GetAccountServiceImplPort"), GetAccountServiceImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetAccountServiceImpl
     */
    @WebEndpoint(name = "GetAccountServiceImplPort")
    public GetAccountServiceImpl getGetAccountServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.soap.com/", "GetAccountServiceImplPort"), GetAccountServiceImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GETACCOUNTSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw GETACCOUNTSERVICEIMPLSERVICE_EXCEPTION;
        }
        return GETACCOUNTSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
